-- --------------------------------------------------------
-- Servidor:                     cm-kls.cluster-cu0eljf5y2ht.us-east-1.rds.amazonaws.com
-- Versão do servidor:           5.6.10-log - MySQL Community Server (GPL)
-- OS do Servidor:               Linux
-- HeidiSQL Versão:              10.1.0.5484
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Copiando estrutura para tabela prod_kls.tbl_indicadores_di2
CREATE TABLE IF NOT EXISTS `tbl_indicadores_di2` (
  `COD_UNIDADE` varchar(100) DEFAULT NULL,
  `UNIDADE` varchar(100) DEFAULT NULL,
  `ID_CURSO_KLS` bigint(20) DEFAULT '0',
  `COD_CURSO_KLS` varchar(100) DEFAULT NULL,
  `NOME_CURSO_KLS` varchar(200) DEFAULT NULL,
  `ID_CURSO` bigint(20) DEFAULT NULL,
  `NOME_CURSO` varchar(100) DEFAULT NULL,
  `FULLNAME` varchar(200) DEFAULT NULL,
  `ID_Categoria` bigint(20) DEFAULT NULL,
  `Nome_Categoria` varchar(100) DEFAULT NULL,
  `ID_GRUPO` bigint(20) DEFAULT NULL,
  `GRUPO` varchar(100) DEFAULT NULL,
  `USERID` bigint(20) DEFAULT NULL,
  `LOGIN` varchar(100) DEFAULT NULL,
  `NOME` varchar(200) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `DataVinculoDisciplina` varchar(100) DEFAULT NULL,
  `PrimeiroAcessoDisciplina` varchar(100) DEFAULT NULL,
  `UltimoAcessoDisciplina` varchar(100) DEFAULT NULL,
  `QuantDiasAcesso` int(11) DEFAULT NULL,
  `ATIVIDADE_1_ALUNO` varchar(100) DEFAULT NULL,
  `QUIZ_U1S1_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U1S1_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U1S2_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U1S2_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U1S3_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U1S3_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U1S4_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U1S4_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U1` varchar(50) DEFAULT NULL,
  `QUIZ_U2S1_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U2S1_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U2S2_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U2S2_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U2S3_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U2S3_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U2S4_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U2S4_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U2` varchar(50) DEFAULT NULL,
  `QUIZ_U3S1_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U3S1_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U3S2_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U3S2_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U3S3_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U3S3_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U3S4_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U3S4_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U3` varchar(50) DEFAULT NULL,
  `QUIZ_U4S1_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U4S1_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U4S2_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U4S2_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U4S3_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U4S3_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U4S4_DIAGNOSTICA` varchar(50) DEFAULT NULL,
  `QUIZ_U4S4_APRENDIZAGEM` varchar(50) DEFAULT NULL,
  `QUIZ_U4` varchar(50) DEFAULT NULL,
  `TUTOR_ID` bigint(20) DEFAULT NULL,
  `TUTOR_LOGIN` varchar(100) DEFAULT NULL,
  `TUTOR_EMAIL` varchar(100) DEFAULT NULL,
  `TUTOR_DataVinculo` varchar(100) DEFAULT NULL,
  `TUTOR_NOME` varchar(200) DEFAULT NULL,
  `TUTOR_PrimeiroAcesso` varchar(100) DEFAULT NULL,
  `TUTOR_UltimoAcesso` varchar(100) DEFAULT NULL,
  `ATIVIDADE_1_AVALIACAO` varchar(100) DEFAULT NULL,
  `ATIVIDADE_1_NOTA` varchar(50) DEFAULT NULL,
  KEY `idx_cursogrupo` (`ID_CURSO`,`ID_GRUPO`),
  KEY `idx_usercurso` (`ID_CURSO`,`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Exportação de dados foi desmarcado.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
