-- --------------------------------------------------------
-- Servidor:                     cm-kls.cluster-cu0eljf5y2ht.us-east-1.rds.amazonaws.com
-- Versão do servidor:           5.6.10-log - MySQL Community Server (GPL)
-- OS do Servidor:               Linux
-- HeidiSQL Versão:              10.1.0.5484
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Copiando estrutura para procedure prod_kls.PRC_CARGA
DELIMITER //
CREATE DEFINER=`jsilva`@`%` PROCEDURE `PRC_CARGA`()
MAIN: BEGIN

DECLARE V_CARGA INT;
DECLARE V_PROCESSO_ATIVO INT;
DECLARE V_OPERACAO_ID INT;
DECLARE V_SALAS INT;
DECLARE V_USUARIOS INT;
DECLARE V_COMENTARIO VARCHAR(255);
DECLARE V_INCLUSOES INT;
DECLARE V_BLOQUEIOS INT;
DECLARE V_TOTAL INT;
DECLARE FUSOHORARIO INT(11);

update tbl_event_set set EXECUT=0 where NAME='evt_relatorios';

SELECT IF(EXECUT=0,3,2) INTO FUSOHORARIO FROM tbl_event_set WHERE NAME='summertime';

SET V_PROCESSO_ATIVO=0;
SET V_SALAS=0;

update tbl_event_set set EXECUT=1 where NAME='evt_carga';  

  IF (FNC_EVENT_SET('evt_carga') = 0) THEN
    
    SELECT 
      CASE WHEN TERMINO IS NULL THEN 0 ELSE 1 END 
      INTO V_PROCESSO_ATIVO
    FROM anh_carga_log ORDER BY ID DESC LIMIT 1;
    
    IF (V_PROCESSO_ATIVO=0) THEN
      INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO, TERMINO) 
      VALUES (NOW()-interval FUSOHORARIO hour,'CARGA ANTERIOR NÃO CONCLUIDA - PROCESSO INTERROMPIDO', NOW()-interval FUSOHORARIO hour, NOW()-interval FUSOHORARIO hour);
      LEAVE MAIN;        
    END IF;
              
    INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO, TERMINO) 
    VALUES (NOW()-interval FUSOHORARIO hour,'CARGA NÃO PREPARADA PARA EXECUÇÃO - PROCESSO INTERROMPIDO', NOW()-interval FUSOHORARIO hour, NOW()-interval FUSOHORARIO hour);
    LEAVE MAIN;
  END IF;

/** IF (FNC_CHECK_KHUB()>0) THEN
    INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO, TERMINO) 
    VALUES (NOW()-interval FUSOHORARIO hour,'FALHA NA VALIDAÇAO DE DADOS KHUB - CARGA INTERROMPIDA', NOW()-interval FUSOHORARIO hour, NOW()-interval FUSOHORARIO hour);
    LEAVE MAIN;
END IF;      
**/
update tbl_event_set set EXECUT=0 where NAME='evt_carga';  

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ATUALIZAÇÃO DAS KLS PARA NANO CERTIFICAÇÃO', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
UPDATE anh_nano_certificacao anh
JOIN kls_lms_instituicao i ON i.cd_instituicao=anh.cd_instituicao
JOIN kls_lms_curso c ON c.id_ies=i.id_ies AND c.cd_curso=anh.cd_curso AND c.fl_etl_atu REGEXP '[NA]'
JOIN kls_lms_disciplina d ON d.id_ies=i.id_ies AND d.cd_disciplina=anh.cd_disciplina AND d.fl_etl_atu REGEXP '[NA]'
JOIN kls_lms_tipo_modelo tm ON tm.id_tp_modelo=d.id_tp_modelo AND tm.sigla=anh.tipo_modelo
JOIN kls_lms_curso_disciplina cd ON cd.id_curso=c.id_curso AND cd.id_disciplina=d.id_disciplina AND cd.fl_etl_atu REGEXP '[NA]'
JOIN kls_lms_turmas t ON t.id_curso_disciplina=cd.id_curso_disciplina AND t.cd_turma=anh.cd_turma_de
SET t.shortname=anh.shortname_turma_para
WHERE t.shortname<>anh.shortname_turma_para AND c.nm_curso REGEXP 'Nano Certificação';
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ATUALIZAÇÃO DE TABELAS ESPELHO', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_USER_MDL();  
CALL PRC_CURSO_MDL();
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';
COMMIT;

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,NULL, NOW()-interval FUSOHORARIO hour);
SET V_CARGA=LAST_INSERT_ID();
UPDATE anh_carga_log SET ETAPA=CONCAT('PROCEDIMENTO DE CARGA - ',NOW()-interval FUSOHORARIO hour) WHERE ID=V_CARGA;


INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'MARCAÇÃO DE AGRUPAMENTOS E SHORTNAMES', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_AGRUPAMENTO;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'INSERÇÃO DE ACESSOS MANUAIS', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_ACESSOS_MANUAIS;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;


INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO BLOQUEIOS DE USUÁRIOS', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_BLOQUEAR_USUARIOS;
SELECT COUNT(1) INTO V_USUARIOS FROM anh_import_aluno WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK';
SET V_COMENTARIO=CONCAT('USUARIOS BLOQUEADOS: ',V_USUARIOS);
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO NOVOS USUÁRIOS', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_INCLUIR_USUARIOS;
CALL PRC_USER_MDL();  
SELECT COUNT(1) INTO V_USUARIOS FROM anh_import_aluno WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK';
SET V_COMENTARIO=CONCAT('USUARIOS NOVOS: ',V_USUARIOS);
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ATRIBUIÇÃO E AJUSTE DE TEMAS', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_THEME;
CALL PRC_AJUSTA_TEMA;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'SUSPENSÃO DE TUTORES', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_TUTORES_SUSPENSOS;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS AMP', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_AMP_ALUNO;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (AMP) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (AMP) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS AMI', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_AMI_ALUNO;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (AMI) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (AMI) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS NPJ', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_NPJV_ALUNO;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (NPJV) anh JOIN mdl_course c ON c.shortname=anh.shortname WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (NPJV) anh JOIN mdl_course c ON c.shortname=anh.shortname WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL (NPJ): ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ALOCANDO ALUNOS DE NPJ', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_ALOCAR_TUTORES_NPJ;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS NPJ PRESENCIAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_NPJP_ALUNO;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (NPJP) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (NPJP) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS TCC VIRTUAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_TCCV_ALUNO;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ALOCANDO ALUNOS DE TCC VIRTUAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_ALOCAR_TUTORES_TCC;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (TCCV) anh JOIN mdl_course c ON c.shortname=anh.shortname WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND c.SHORTNAME LIKE 'TCCV%' AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (TCCV) anh JOIN mdl_course c ON c.shortname=anh.shortname WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND c.SHORTNAME LIKE 'TCCV%' AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL (TCC VIRTUAL): ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS TCC PRESENCIAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_TCCP_ALUNO; 
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (TCCP) WHERE SHORTNAME LIKE 'TCCP%' AND DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (TCCP) WHERE SHORTNAME LIKE 'TCCP%' AND DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS DI VIRTUAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_DI_ALUNO;
CALL PRC_ALOCAR_TUTORES_DI;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (DI) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (DI) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS DIB VIRTUAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_DIBV_ALUNO;
CALL PRC_ALOCAR_TUTORES_DIB;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (DIBV) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (DIBV) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS DIB PRESENCIAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_DIBP_ALUNO;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (DIBP) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (DIBP) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS DI PRESENCIAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_DIP_ALUNO;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (DIP) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (DIP) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS HIB VIRTUAL (HIBV)', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_HIBV_ALUNO;
CALL PRC_ALOCAR_TUTORES_HIBV;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (HIBV) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (HIBV) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS HIBAMPP', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_HIBAMPP_ALUNO;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (HAMPP) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (HAMPP) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS HIBAMIP', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_HIBAMIP_ALUNO;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (HAMIP) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (HAMIP) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS ESTÁGIO VIRTUAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_ESTV_ALUNO;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ALOCANDO ALUNOS DE ESTÁGIO VIRTUAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_ALOCAR_TUTORES_EST;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (ESTV) anh JOIN mdl_course c ON c.shortname=anh.shortname WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND c.SHORTNAME LIKE 'ESTV%' AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (ESTV) anh JOIN mdl_course c ON c.shortname=anh.shortname WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND c.SHORTNAME LIKE 'ESTV%' AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL (EST VIRTUAL): ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS ESTÁGIO PRESENCIAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_ESTP_ALUNO;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (ESTP) WHERE SHORTNAME LIKE 'ESTP%' AND DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (ESTP) WHERE SHORTNAME LIKE 'ESTP%' AND DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS ED VIRTUAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_EDV_ALUNO;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (EDV) anh JOIN mdl_course c ON c.shortname=anh.shortname WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (EDV) anh JOIN mdl_course c ON c.shortname=anh.shortname WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ALOCANDO ALUNOS DE ED 1', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_ALOCAR_TUTORES_ED1234;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (EDV) anh JOIN mdl_course c ON c.shortname=anh.shortname and c.summary REGEXP '^ED1$' WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (EDV) anh JOIN mdl_course c ON c.shortname=anh.shortname and c.summary REGEXP '^ED1$' WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL (ED 1): ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ALOCANDO ALUNOS DE ED 5,6 e 7', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_ALOCAR_TUTORES_ED567;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (EDV) anh JOIN mdl_course c ON c.shortname=anh.shortname and c.summary REGEXP '^ED[567]$' WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (EDV) anh JOIN mdl_course c ON c.shortname=anh.shortname and c.summary REGEXP '^ED[567]$' WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL (ED 5-7): ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ALOCANDO ALUNOS DE ED 8, 9 E 10', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_ALOCAR_TUTORES_ED8910;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (EDV) anh JOIN mdl_course c ON c.shortname=anh.shortname and c.summary REGEXP '^ED([89]|10)$' WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (EDV) anh JOIN mdl_course c ON c.shortname=anh.shortname and c.summary REGEXP '^ED([89]|10)$' WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL (ED 8-10): ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS DE ALUNOS ED PRESENCIAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_EDP_ALUNO;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (EDP) anh JOIN mdl_course c ON c.shortname=anh.shortname WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK' AND ROLE='student';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (EDP) anh JOIN mdl_course c ON c.shortname=anh.shortname WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK' AND ROLE='student';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'CARGA ACADEMICA', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_ACADEMICO;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'OBTENDO INCLUSÕES E BLOQUEIOS SALA COORDENADOR', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_SALACOORD;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (SCD) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (SCD) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'INCLUINDO NOVOS USUÁRIOS NA HOME', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_CARGA_HOME;
SELECT COUNT(1) INTO V_INCLUSOES FROM anh_import_aluno_curso PARTITION (KLS) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='I' AND STATUS='OK';
SELECT COUNT(1) INTO V_BLOQUEIOS FROM anh_import_aluno_curso PARTITION (KLS) WHERE DATA_IMPORTACAO=date_format(NOW()-interval FUSOHORARIO hour,'%Y-%m-%d') AND SITUACAO='B' AND STATUS='OK';
SET V_TOTAL=V_INCLUSOES+V_BLOQUEIOS;
SET V_COMENTARIO=CONCAT('TOTAL: ',V_TOTAL,' (INCLUSOES: ',V_INCLUSOES,' / BLOQUEIOS: ',V_BLOQUEIOS,')');
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour,COMENTARIO=V_COMENTARIO WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

/** INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'AJUSTE DE MATRICULAS DE TUTORES', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_MATRICULA_TUTOR;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO=''; **/

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ATUALIZANDO DISCIPLINA x AREA FORMACAO', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_ATUALIZA_TMP_ALUNO;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'AJUSTE DO NOME DO TUTOR DE ACORDO COM O SGT', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_ATUALIZA_NOME_TUTOR;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'MIGRAÇÃO DO ARMÁRIO DO PROFESSOR', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_MIGRA_ARMARIO;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'AJUSTE DA SUBMISSÃO', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_AJUSTE_SUBMISSAO;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'LIMPEZA DE GRUPOS', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_LIMPA_GRUPOS;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ATUALIZAÇÃO DE TABELAS ESPELHO', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_USER_MDL();  
CALL PRC_CURSO_MDL();
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ATUALIZAÇÃO DE MIGRAÇÃO DO PDE', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_MIGRACAO_PDE();  
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'AJUSTE DOS NOMES DOS USUÁRIOS E NOME SOCIAL', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
call PRC_AJUSTA_NOME_USUARIO;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ATUALIZANDO PARTIÇÃO DE TUTORES - ACADEMICO', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();

insert into anh_academico_matricula (id_matricula_atual, unidade, curso, username, 
                         shortname, role, grupo,
                        data_matricula, origem, sigla)
select
  0, 'TUTOR', 'TUTOR' ,
  anh.tutor, anh.shortname, 
  'tutor', anh.grupo, min(anh.data_matricula),
  'CARGA', 'TUT'
from anh_aluno_matricula anh
left join anh_academico_matricula partition (tut) acd on 
      acd.username=anh.tutor and 
      acd.shortname=anh.shortname
where anh.tutor REGEXP  'TUTOR' and acd.id is null
group by anh.tutor, anh.shortname, anh.grupo;

UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ATUALIZANDO QTD DE ALUNOS DO TUTOR', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
update mdl_sgt_usuario u
join mdl_sgt_usuario_moodle umo on u.id = umo.id_usuario_id
set u.qtde_alunos = (select count(distinct a.USERNAME)
from anh_aluno_matricula a
where a.tutor = umo.mdl_username);
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'ATRIBUIÇÃO DE IMAGEM PADRÃO PARA NOVOS CURSOS', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
CALL PRC_IMAGEM_PADRAO;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_CARGA;
update tbl_event_set set EXECUT=1 where NAME='evt_relatorios';
update tbl_event_set set EXECUT=1 where NAME='evt_carga';  

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'REMOVENDO ASSOCIAÇÕES INVALIDAS DE GRUPOS DE TUTOR', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();
delete gm from mdl_groups g
join mdl_course c on c.id=g.courseid
join mdl_groups_members gm on gm.groupid=g.id
join mdl_user u on u.id=gm.userid and u.mnethostid=1
join  anh_aluno_matricula anh on anh.username=u.username and anh.shortname=c.shortname and anh.grupo regexp 'TUTOR'
where 
  g.description regexp 'TUTOR'
  AND 
  g.description<>anh.grupo;
UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';

INSERT INTO anh_carga_log (DATA_CARGA,ETAPA,INICIO) VALUES (NOW()-interval FUSOHORARIO hour,'CORREÇÃO DO ID DO PROFESSOR NA MIGRACAO DO ARMARIO', NOW()-interval FUSOHORARIO hour);
SET V_OPERACAO_ID=LAST_INSERT_ID();

update mdl_question_categories qc
join mdl_question q on q.category=qc.id
join mdl_user u on u.username=qc.name and u.mnethostid=1
set q.createdby=u.id, q.modifiedby=u.id
where qc.name regexp '^p\_' and q.createdby<>u.id;

UPDATE anh_carga_log SET TERMINO=NOW()-interval FUSOHORARIO hour WHERE ID=V_OPERACAO_ID;
SET V_COMENTARIO='';
  
END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
