-- --------------------------------------------------------
-- Servidor:                     cm-kls.cluster-cu0eljf5y2ht.us-east-1.rds.amazonaws.com
-- Versão do servidor:           5.6.10-log - MySQL Community Server (GPL)
-- OS do Servidor:               Linux
-- HeidiSQL Versão:              10.1.0.5484
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Copiando estrutura para tabela prod_kls.SISCON_REFERENCIAS
CREATE TABLE IF NOT EXISTS `SISCON_REFERENCIAS` (
  `ID_REFERENCIA` int(11) NOT NULL,
  `TITULO_REFERENCIA` varchar(255) DEFAULT NULL,
  `SUBTITULO_REFERENCIA` varchar(255) DEFAULT NULL,
  `DSC_REFERENCIA` varchar(255) DEFAULT NULL,
  `LINK` varchar(255) DEFAULT NULL,
  `TP_REFERENCIA` int(11) NOT NULL,
  `TIPO_SISCON` int(11) DEFAULT NULL,
  `AUTORES` varchar(255) DEFAULT NULL,
  `EDICAO` int(11) DEFAULT NULL,
  `NUM_PAGINAS` int(11) DEFAULT NULL,
  `VOLUME` int(11) DEFAULT NULL,
  `SERIE` int(11) DEFAULT NULL,
  `LOCAL` varchar(255) DEFAULT NULL,
  `EDITORA` varchar(255) DEFAULT NULL,
  `ANO_PUBLICACAO` varchar(255) DEFAULT NULL,
  `ISBN` varchar(45) DEFAULT NULL,
  `FASCICULO` int(11) DEFAULT NULL,
  `DATA_PUBLICACAO` date DEFAULT NULL,
  `DIRETORES` varchar(255) DEFAULT NULL,
  `PRODUTORES` varchar(255) DEFAULT NULL,
  `PRODUTORA` varchar(255) DEFAULT NULL,
  `DURACAO` int(11) DEFAULT NULL,
  `QUANTIDADE` int(11) DEFAULT NULL,
  `DIGITAL` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_REFERENCIA`,`TP_REFERENCIA`),
  KEY `fk_SISCON_REFERENCIAS_SISCON_TIPO_REFERENCIA1` (`TP_REFERENCIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Exportação de dados foi desmarcado.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
