-- --------------------------------------------------------
-- Servidor:                     cm-kls.cluster-cu0eljf5y2ht.us-east-1.rds.amazonaws.com
-- Versão do servidor:           5.6.10-log - MySQL Community Server (GPL)
-- OS do Servidor:               Linux
-- HeidiSQL Versão:              10.1.0.5484
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Copiando estrutura para tabela prod_kls.anh_import_aluno_curso
CREATE TABLE IF NOT EXISTS `anh_import_aluno_curso` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_PESSOA_CURSO` int(11) DEFAULT NULL,
  `ID_PES_CUR_DISC` int(11) DEFAULT '0',
  `ID_PESSOA_TURMA` int(11) DEFAULT '0',
  `SIGLA` varchar(20) NOT NULL DEFAULT '0',
  `ORIGEM` varchar(15) DEFAULT NULL,
  `USERNAME` varchar(50) DEFAULT NULL,
  `SHORTNAME` varchar(50) DEFAULT NULL,
  `CODIGO_POLO` varchar(10) DEFAULT NULL,
  `NOME_POLO` varchar(100) DEFAULT NULL,
  `CODIGO_CURSO` varchar(20) DEFAULT NULL,
  `NOME_CURSO` varchar(100) DEFAULT NULL,
  `CODIGO_DISCIPLINA` varchar(20) DEFAULT NULL,
  `NOME_DISCIPLINA` varchar(100) DEFAULT NULL,
  `SERIE_ALUNO` varchar(20) DEFAULT NULL,
  `TURNO_CURSO` varchar(15) DEFAULT NULL,
  `TURMA_ALUNO` varchar(20) DEFAULT NULL,
  `GRUPO` varchar(50) DEFAULT NULL,
  `TUTOR` varchar(30) DEFAULT NULL,
  `ROLE` varchar(20) DEFAULT NULL,
  `DATA_IMPORTACAO` date DEFAULT NULL,
  `SITUACAO` varchar(10) DEFAULT NULL,
  `STATUS` varchar(10) DEFAULT NULL,
  `NOVA_TENTATIVA` date DEFAULT NULL,
  `LOG` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`ID`,`SIGLA`),
  KEY `idx_role` (`ROLE`),
  KEY `idx_situacao` (`SITUACAO`),
  KEY `idx_username` (`USERNAME`),
  KEY `idx_grupo` (`GRUPO`),
  KEY `idx_data_importacao` (`DATA_IMPORTACAO`,`NOVA_TENTATIVA`),
  KEY `idx_unidade` (`CODIGO_POLO`,`CODIGO_CURSO`),
  KEY `idx_id_pessoa_disciplina` (`ID_PES_CUR_DISC`),
  KEY `idx_sigla` (`SHORTNAME`,`SIGLA`,`USERNAME`),
  KEY `idx_status` (`STATUS`),
  KEY `idx_shortname` (`USERNAME`,`SHORTNAME`)
) ENGINE=InnoDB AUTO_INCREMENT=7749243 DEFAULT CHARSET=utf8
/*!50500 PARTITION BY LIST  COLUMNS(SIGLA)
(PARTITION DIP VALUES IN ('DIP') ENGINE = InnoDB,
 PARTITION DIBV VALUES IN ('DIBV') ENGINE = InnoDB,
 PARTITION DIBP VALUES IN ('DIBP') ENGINE = InnoDB,
 PARTITION TCCV VALUES IN ('TCCV') ENGINE = InnoDB,
 PARTITION TCCP VALUES IN ('TCCP') ENGINE = InnoDB,
 PARTITION ESTV VALUES IN ('ESTV') ENGINE = InnoDB,
 PARTITION ESTP VALUES IN ('ESTP') ENGINE = InnoDB,
 PARTITION EDV VALUES IN ('EDV') ENGINE = InnoDB,
 PARTITION EDP VALUES IN ('EDP') ENGINE = InnoDB,
 PARTITION NPJV VALUES IN ('NPJV') ENGINE = InnoDB,
 PARTITION NPJP VALUES IN ('NPJP') ENGINE = InnoDB,
 PARTITION AMI VALUES IN ('AMI') ENGINE = InnoDB,
 PARTITION AMP VALUES IN ('AMP') ENGINE = InnoDB,
 PARTITION SCD VALUES IN ('SCD') ENGINE = InnoDB,
 PARTITION AUTOLOGIN VALUES IN ('EDCL') ENGINE = InnoDB,
 PARTITION PVDV VALUES IN ('PVDV') ENGINE = InnoDB,
 PARTITION PVDP VALUES IN ('PVDP') ENGINE = InnoDB,
 PARTITION di VALUES IN ('DI') ENGINE = InnoDB,
 PARTITION KLS VALUES IN ('KLS') ENGINE = InnoDB,
 PARTITION SPF VALUES IN ('SPF') ENGINE = InnoDB,
 PARTITION HAMPP VALUES IN ('HAMPP') ENGINE = InnoDB,
 PARTITION HIBV VALUES IN ('HIBV') ENGINE = InnoDB,
 PARTITION HAMIP VALUES IN ('HAMIP') ENGINE = InnoDB) */;

-- Exportação de dados foi desmarcado.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
